# Schemas module — Pydantic request/response models
from app.schemas.common import ApiResponse, ErrorDetail
from app.schemas.opportunity import (
    EligibilityRead,
    OpportunityCreateRequest,
    OpportunityDetail,
    OpportunityListResponse,
    OpportunityRead,
    OpportunitySkillItem,
    OpportunitySkillRead,
    OpportunitySourceRead,
    PaginationMeta,
)
from app.schemas.user import (
    AuthResponseData,
    InterestItem,
    InterestRead,
    SkillItem,
    SkillRead,
    TokenData,
    UserBase,
    UserInterestsUpdateRequest,
    UserLoginRequest,
    UserProfileResponse,
    UserProfileUpdateRequest,
    UserRead,
    UserRegisterRequest,
    UserSkillsUpdateRequest,
)

__all__ = [
    "ApiResponse",
    "ErrorDetail",
    "UserBase",
    "UserRegisterRequest",
    "UserLoginRequest",
    "UserRead",
    "UserProfileResponse",
    "UserProfileUpdateRequest",
    "SkillItem",
    "SkillRead",
    "UserSkillsUpdateRequest",
    "InterestItem",
    "InterestRead",
    "UserInterestsUpdateRequest",
    "TokenData",
    "AuthResponseData",
    "OpportunityCreateRequest",
    "OpportunityRead",
    "OpportunityDetail",
    "OpportunitySkillItem",
    "OpportunitySkillRead",
    "OpportunitySourceRead",
    "OpportunityListResponse",
    "PaginationMeta",
    "EligibilityRead",
]
